spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:hodolog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    web:
      pageable:
        one-indexed-parameters: true
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: create-drop
#    show-sql: true
#    generate-ddl: true

